const Physics = {
  Easy: [
    "What is the unit of force?",
    "What is the SI unit of electric current?",
    "What is the resistance measured in?",
    "What is the SI unit of energy?",
    "What law states that every action has an equal and opposite reaction?",
    "What is the SI unit of power?",
    "What is the acceleration due to gravity on Earth?",
    "What property of a body resists a change in its state of motion?",
    "What is the SI unit of electric charge?",
    "What is the force that opposes motion between two surfaces in contact?",
    "What type of energy is associated with motion?",
    "What law states that the total energy of an isolated system is constant?",
    "What is the SI unit of frequency?",
    "What law states that the pressure of a gas is inversely proportional to its volume at constant temperature?",
    "What is the SI unit of electric potential difference?",
    "What is the SI unit of magnetic flux?",
    "What is the SI unit of temperature?",
    "What is the phenomenon where a wave changes direction as it passes through a medium?",
    "What law relates the pressure and volume of a gas at constant temperature?",
    "What is the measure of the average kinetic energy of particles in a substance?",
  ],
  Medium: [
    "What is the difference between speed and velocity?",
    "Explain the concept of torque.",
    "What is the photoelectric effect?",
    "Define angular momentum.",
    "What is the principle of conservation of momentum?",
    "Explain how a capacitor works.",
    "What is the Doppler effect?",
    "Define buoyant force.",
    "Explain the concept of wave-particle duality.",
    "What is the difference between elastic and inelastic collisions?",
    "Define electric potential energy.",
    "Explain the First Law of Thermodynamics.",
    "What is the difference between series and parallel circuits?",
    "Define half-life in the context of radioactive decay.",
    "Explain the concept of centripetal force.",
    "What is Hooke's Law?",
    "Define the work-energy theorem.",
    "Explain the function of a concave lens.",
    "What is the difference between mass and weight?",
    "Define magnetic induction.",
  ],
  Hard: [
    "Explain the concept of quantum entanglement.",
    "Describe the Heisenberg Uncertainty Principle.",
    "What is the Schwarzschild radius in the context of black holes?",
    "Explain the concept of dark matter.",
    "Define the Casimir effect.",
    "What is the significance of Planck's constant in quantum mechanics?",
    "Explain the concept of quantum tunneling.",
    "Define the Riemann curvature tensor in the context of general relativity.",
    "What is the difference between bosons and fermions?",
    "Describe the double-slit experiment and its implications for quantum mechanics.",
    "Explain the concept of Yang-Mills theory in particle physics.",
    "Define the Chandrasekhar limit and its significance in astrophysics.",
    "What is the difference between the strong force and the weak force in particle physics?",
    "Explain the concept of time dilation in the theory of relativity.",
    "Define the Magnus effect in fluid dynamics.",
    "What is the nature of dark energy and its role in the expansion of the universe?",
    "Explain the concept of supersymmetry.",
    "Describe the three laws of thermodynamics.",
    "What is the role of the Higgs boson in particle physics?",
    "Explain the concept of non-abelian gauge symmetry.",
  ],
};

module.exports = {
  Physics,
};
